### PR TITLE
Potential fix to the tooltip with special characters  bug

### LINKED ISSUE #750: graphviz draw tooltip with special characters
### Information

- **rustworkx version**:  0.12.1
- **Python version**: 3.9.13
- **Rust version**: NA
- **Operating system**: Windows 10

### What is the current behavior?

Adding a `\n` or `:` character to the tooltip throws this error:

```
Error: <stdin>: syntax error in line 4 near ']'      
Traceback (most recent call last):
  File main.py", line 6, in <module>
    graphviz_draw(
  File "venv\lib\site-packages\rustworkx\visualization\graphviz.py", line 199, in graphviz_draw
    subprocess.run(
  File "AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,  
subprocess.CalledProcessError: Command '['dot', '-T', 'svg', '-o', 'graph.svg']' returned non-zero exit status 1.
```

### What is the expected behavior?
I would like the tooltip to support special characters such as `\n` and `:`, like label does.
In http://magjac.com/graphviz-visual-editor/, I'm allowed to do that with:
```
digraph {
  label="Graph Label"
  Node1 [tooltip="Node1 Tooltip\nlinebreak in tooltip: it's fine"]
}
```

### Steps to reproduce the problem
```
import rustworkx as rx
from rustworkx.visualization import graphviz_draw

graphviz_draw(
    rx.generators.path_graph(2),
    filename="graph.svg",
    image_type="svg",
    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
)
```

### PR DESCRIPTION
**Pull request by anushkrishnav**
Fixes #750 

Updated the fn attr_map_to_string function 
I can add a separate function to handle the escape values if needed 
```
fn escape_graphviz_value(value: &str) -> String {
    value
        .replace("\\", "\\\\")  // Escape backslashes first
        .replace("\"", "\\\"")  // Escape double quotes
        .replace("\n", "\\n")   // Escape newlines
        .replace(":", "\\:")    // Escape colons
}
```

Will finish up docs and tests once the solution is satisfactory 
- [ ] I ran rustfmt locally
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
Did you push the correct branch in your PR? The code change here is adding a print statement (it looks like a debug print) and not fixing the bug.

**Comment by anushkrishnav** [comment]
> Did you push the correct branch in your PR? The code change here is adding a print statement (it looks like a debug print) and not fixing the bug.

ohh sorry Let me check whats happening,

**Comment by anushkrishnav** [comment]
@mtreinish Sorry about the print statement , is this how the output must look like ?
image

it would be saved as a graph.svg ??

I am sorry looks like i forgot to push the update , Silly

File: src/dot_utils.rs [hunk 1]
```diff
@@ -82,15 +82,15 @@ fn attr_map_to_string<'a>(
...
     let attr_string = attrs
         .iter()
         .map(|(key, value)| {
-            if key == "label" {
-                format!("{}=\"{}\"", key, value)
-            } else {
-                format!("{}={}", key, value)
-            }
+            let escaped_value = value
+                .replace('\\', "\\\\") // Escape backslashes first
```
Comment (IvanIsCoding) [inline src/dot_utils.rs:89]: Is there a dictionary of values that we should escape? Just wondering

**Review by IvanIsCoding — COMMENTED** [review]
I think the idea is good, but we definetely need to check if we covered all possible characters that need escaping. And add tests

File: src/dot_utils.rs (hunk 1 above)
Comment (anushkrishnav) [reply src/dot_utils.rs:89]: There is a library we can make use serde_json library to do this instead

**Comment by anushkrishnav** [comment]
> I think the idea is good, but we definitely need to check if we covered all possible characters that need escaping. And add tests

I belive using a package like serde json should be a better way to do it that building a dictionary of cases that we cant escaped

**Comment by anushkrishnav** [comment]
> I think the idea is good, but we definetely need to check if we covered all possible characters that need escaping. And add tests

Yes We can add a custom test case that tests for combinations of escape sequences

File: src/dot_utils.rs (hunk 1 above)
Comment (anushkrishnav) [reply src/dot_utils.rs]: Ideally there is 6
https://static.rust-lang.org/doc/master/reference.html#byte-escapes

Comment (anushkrishnav) [reply src/dot_utils.rs]: > Is there a dictionary of values that we should escape? Just wondering

Ideally there are 6, 
https://static.rust-lang.org/doc/master/reference.html#byte-escapes

File: tests/visualization/test_graphviz.py [hunk 2]
```diff
@@ -150,3 +150,47 @@ def test_filename(self):
...
+            insert_at_tooltip = random.randint(0, len(base_tooltip))
+            
+            # Generate label and tooltip using list comprehension and join
+            label = ''.join([base_label[:insert_at_label], random.choice(escapes), base_label[insert_at_label:]])
+            tooltip = ''.join([base_tooltip[:insert_at_tooltip], random.choice(escapes), base_tooltip[insert_at_tooltip:]])
+            
+            return {"label": label, "tooltip": tooltip}
+        
+        # Draw the graph using graphviz_draw
+        image = graphviz_draw(
```
Comment (IvanIsCoding) [inline tests/visualization/test_graphviz.py:178]: I think it would be better to test with https://www.rustworkx.org/dev/apiref/rustworkx.PyGraph.to_dot.html

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:178]: sounds good will work on em

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:178]: Do you want me to run that code or ?

Comment (IvanIsCoding) [reply tests/visualization/test_graphviz.py:178]: I want you to avoid writing temporary files to the disk for the unit tests. For the GitHub CI, we found those tests very flaky on macOS. So I suggested that method as a way of testing the fix with only in-memory operations

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:178]: @IvanIsCoding , you want me to adapt my code to use this 
```
with tempfile.TemporaryDirectory() as tmpdirname:
    tmp_path = os.path.join(tmpdirname, 'dag.png')
    dot.write_png(tmp_path)
    image = Image.open(tmp_path)
    os.remove(tmp_path)
```
Or make that entire code as the test case ?

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py]: Sounds good, Update the code with the recommendation, let me know if it needs any changes

File: tests/visualization/test_graphviz.py [hunk 3]
```diff
@@ -14,8 +14,9 @@
 import subprocess
 import tempfile
 import unittest
-
+import random
 import rustworkx
+import pydot
```
Comment (IvanIsCoding) [inline tests/visualization/test_graphviz.py:19]: You don’t want to use pydot as a dependency. We have stopped using it a year ago

File: tests/visualization/test_graphviz.py [hunk 4]
```diff
@@ -150,3 +151,50 @@ def test_filename(self):
...
+                                random.choice(escapes),
+                                base_tooltip[insert_at_tooltip:]
+                            ])
+            return {"label": label, "tooltip": tooltip}
+
+        # Draw the graph using graphviz_draw
+        dot_str = graph.to_dot(node_attr)
+        dot = pydot.graph_from_dot_data(dot_str)[0]
+
+        with tempfile.TemporaryDirectory() as tmpdirname:
```
Comment (IvanIsCoding) [inline tests/visualization/test_graphviz.py:195]: This is exactly what you should avoid. Instead of writing the image, just check if the string from `to_dot` contains the escaped characters

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:195]: Got it, Thank you for the clarification

Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py]: I have updated the code to check the to_dot for escape sequence, also looped through all possible ones to ensure we don't miss any

**Comment by IvanIsCoding** [comment]
Rust code is looking good, just two minor things and this will be good to go:
* Add release notes with a graph exemplifying the fix. https://github.com/Qiskit/rustworkx/blob/53868f83c2c100dbd8b4c5f689f075699f2edab5/releasenotes/notes/0.14/add-albert-graph-5a7d393e1fe18e9d.yaml#L9 is a good reference, but you will need to use `graphviz_draw` instead of `mpl_draw`, of course.
* Address the Clippy fail in CI

**Review by IvanIsCoding — APPROVED** [review]
@anushkrishnav I approved the CL but you need to fix the CI errors by running `black`, `cargo clippy`. I also recommend running `nox -edocs` to confirm that the documentation compiles too

**Comment by anushkrishnav** [comment]
> @anushkrishnav I approved the CL but you need to fix the CI errors by running `black`, `cargo clippy`. I also recommend running `nox -edocs` to confirm that the documentation compiles too

Will finish it today, thanks it was fun to work with !!

**Comment by IvanIsCoding** [comment]
> > @anushkrishnav I approved the CL but you need to fix the CI errors by running `black`, `cargo clippy`. I also recommend running `nox -edocs` to confirm that the documentation compiles too
> 
> Will finish it today, thanks it was fun to work with !!

You missed the ruff lint from `nox -elint`. Also seconding `nox -edocs` try to make sure the documentation builds

**Comment by anushkrishnav** [comment]
> > > @anushkrishnav I approved the CL but you need to fix the CI errors by running `black`, `cargo clippy`. I also recommend running `nox -edocs` to confirm that the documentation compiles too
> > 
> > 
> > Will finish it today, thanks it was fun to work with !!
> 
> You missed the ruff lint from `nox -elint`. Also seconding `nox -edocs` try to make sure the documentation builds

I am having some issue with `nox -edocs`

```
nox > jupyter kernelspec list
Available kernels:
  python3    /Users/anushkrishnav/Library/Jupyter/kernels/python3
nox > cd docs
nox > sphinx-build -W -d build/.doctrees -b html source build/html
Running Sphinx v7.1.2

Extension error:
Handler <function _get_versions at 0x1048e1260> for event 'config-inited' threw an exception (exception: Command '['git', 'describe', '--abbrev=0']' returned non-zero exit status 128.)
nox > Command sphinx-build -W -d build/.doctrees -b html source build/html failed with exit code 2
nox > Session docs-3 failed.
```

**Comment by IvanIsCoding** [comment]
We are getting test failures like
```
======================================================================
FAIL: test_graph_to_dot (graph.test_dot.TestDot.test_graph_to_dot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/rustworkx/rustworkx/tests/graph/test_dot.py", line 51, in test_graph_to_dot
    self.assertEqual(expected, res)
AssertionError: 'graph {\n0 [color=black, fillcolor=green, label="a", style=[96 chars]n}\n' != 'graph {\n0 [color="black", fillcolor="green", label="a", st[110 chars]n}\n'
  graph {
- 0 [color=black, fillcolor=green, label="a", style=filled];
+ 0 [color="black", fillcolor="green", label="a", style="filled"];
?          +     +            +     +                   +      +
- 1 [color=black, fillcolor=red, label="a", style=filled];
+ 1 [color="black", fillcolor="red", label="a", style="filled"];
?          +     +            +   +                   +      +
- 0 -- 1 [label="1", name=1];
+ 0 -- 1 [label="1", name="1"];
?                         + +
  }
```

Ideally we would not have any. So you either need to update the test to include the quotes or make the code not generate the quotes. Up to you

File: tests/visualization/test_graphviz.py [hunk 5]
```diff
@@ -150,3 +149,36 @@ def test_filename(self):
         self.assertTrue(os.path.isfile("test_graphviz_filename.svg"))
         if not SAVE_IMAGES:
             self.addCleanup(os.remove, "test_graphviz_filename.svg")
+
+    def test_escape_sequences(self):
```
Comment (IvanIsCoding) [inline tests/visualization/test_graphviz.py:153]: I wonder if the escaping makes all variables have quotes by default

**Review by IvanIsCoding — CHANGES_REQUESTED** [review]

File: tests/visualization/test_graphviz.py (hunk 5 above)
Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:153]: yes, also I feel removing quotes will not be ideal , I will update the expected result

Comment (IvanIsCoding) [reply tests/visualization/test_graphviz.py:153]: As long as it doesn't break the graphs I am fine with either

**Comment by IvanIsCoding** [comment]
> > > > @anushkrishnav I approved the CL but you need to fix the CI errors by running `black`, `cargo clippy`. I also recommend running `nox -edocs` to confirm that the documentation compiles too
> > > 
> > > 
> > > Will finish it today, thanks it was fun to work with !!
> > 
> > 
> > You missed the ruff lint from `nox -elint`. Also seconding `nox -edocs` try to make sure the documentation builds
> 
> I am having some issue with `nox -edocs`
> 
> ```
> nox > jupyter kernelspec list
> Available kernels:
>   python3    /Users/anushkrishnav/Library/Jupyter/kernels/python3
> nox > cd docs
> nox > sphinx-build -W -d build/.doctrees -b html source build/html
> Running Sphinx v7.1.2
> 
> Extension error:
> Handler <function _get_versions at 0x1048e1260> for event 'config-inited' threw an exception (exception: Command '['git', 'describe', '--abbrev=0']' returned non-zero exit status 128.)
> nox > Command sphinx-build -W -d build/.doctrees -b html source build/html failed with exit code 2
> nox > Session docs-3 failed.
> ```

I am going to need a little bit more of the error message output to identify the error. But I have a feeling it is the space identation on the release note. Those are always a bit tricky

File: tests/visualization/test_graphviz.py (hunk 5 above)
Comment (anushkrishnav) [reply tests/visualization/test_graphviz.py:153]: It doesnt, I am trying to see if have quotes is better than not having them but since we are handling special characters it shouldn't be a problem

**Comment by anushkrishnav** [comment]
> > ```
> > 
> > ```
> 
> 
> I am going to need a little bit more of the error message output to identify the error. But I have a feeling it is the space identation on the release note. Those are always a bit tricky

@IvanIsCoding This is the message I am getting from the terminal atm 

```

nox > Running session docs-3
nox > Re-using existing virtual environment at .nox/docs-3.
nox > python -m pip install setuptools-rust fixtures 'testtools>=2.5.0' 'networkx>=2.5' 'scipy>=1.7' 'stestr>=4.1'
nox > python -m pip install '.[all]' -c constraints.txt
nox > python -m pip install -r docs/source/requirements.txt -c constraints.txt
nox > python -m ipykernel install --user
Installed kernelspec python3 in /Users/anushkrishnav/Library/Jupyter/kernels/python3
nox > jupyter kernelspec list
Available kernels:
  python3    /Users/anushkrishnav/Library/Jupyter/kernels/python3
nox > cd docs
nox > sphinx-build -W -d build/.doctrees -b html source build/html
Running Sphinx v7.1.2

Extension error:
Handler <function _get_versions at 0x102505260> for event 'config-inited' threw an exception (exception: Command '['git', 'describe', '--abbrev=0']' returned non-zero exit status 128.)
nox > Command sphinx-build -W -d build/.doctrees -b html source build/html failed with exit code 2
nox > Session docs-3 failed.
```

**Comment by anushkrishnav** [comment]
the issue seems to stems from 
```
'['git', 'describe', '--abbrev=0']'
```
Which ig gets the recent tag ?

**Comment by IvanIsCoding** [comment]
> the issue seems to stems from
> 
> ```
> '['git', 'describe', '--abbrev=0']'
> ```
> 
> Which ig gets the recent tag ?

That is an unrelated error. I think the real one is highlighted in the CI:
```
Error: <stdin>: syntax error in line 2 near '\'

Extension error:
Cell raised uncaught exception:
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[3], line 4
      1 import rustworkx as rx
      2 from rustworkx.visualization import graphviz_draw
----> 4 graphviz_draw(
      5 rx.generators.path_graph(2),
      6 filename="graph.svg",
      7 image_type="svg",
      8 node_attr_fn=lambdax:{"label":"the\nlabel","tooltip":"the\ntooltip"},
      9 )

File ~/work/rustworkx/rustworkx/.nox/docs-3/lib/python3.8/site-packages/rustworkx/visualization/graphviz.py:212, in graphviz_draw(graph, node_attr_fn, edge_attr_fn, graph_attr, filename, image_type, method)
    210     return image
    211 else:
--> 212     subprocess.run(
    213 [prog,"-T",output_format,"-o",filename],
    214 input=dot_str,
    215 check=True,
    216 encoding="utf8",
    217 text=True,
    218 )
    219     return None
```

The release note drawing is throwing an exception when calling graphviz

**Comment by anushkrishnav** [comment]
Okay I see the problem is with the quotes , it helps with the '\' issue

File: src/dot_utils.rs [hunk 6]
```diff
@@ -82,14 +82,15 @@ fn attr_map_to_string<'a>(
     if attrs.is_empty() {
         return Ok("".to_string());
     }
-
     let attr_string = attrs
         .iter()
         .map(|(key, value)| {
+            let escaped_value = serde_json::to_string(value).unwrap();
+            let escaped_value = &escaped_value[1..escaped_value.len() - 1];
             if key == "label" {
```
Comment (IvanIsCoding) [inline src/dot_utils.rs:90]: It looks like you don't need this if statement according to clippy

File: releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+                    rx.generators.path_graph(2),
+                    filename="graph.svg",
+                    image_type="svg",
+                    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
+                )
+
+
+
+
+
```
Comment (IvanIsCoding) [inline releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml:23]:
```suggestion

```

File: src/dot_utils.rs [hunk 8]
```diff
@@ -82,15 +82,12 @@ fn attr_map_to_string<'a>(
...
-
     let attr_string = attrs
         .iter()
         .map(|(key, value)| {
-            if key == "label" {
-                format!("{}=\"{}\"", key, value)
-            } else {
-                format!("{}={}", key, value)
-            }
+            let escaped_value = serde_json::to_string(value).unwrap();
```
Comment (IvanIsCoding) [inline src/dot_utils.rs:88]:
```suggestion
            let escaped_value = serde_json::to_string(value)?;
```

File: src/dot_utils.rs [hunk 9]
```diff
@@ -82,15 +82,12 @@ fn attr_map_to_string<'a>(
...
+            let escaped_value = &escaped_value[1..escaped_value.len() - 1];
```
Comment (IvanIsCoding) [inline src/dot_utils.rs:89]:
```suggestion
            let escaped_value = &escaped_value.get(1..escaped_value.len() - 1)?;
```

**Review by IvanIsCoding — APPROVED** [review]
Leaving some minor change requests as `unwrap()` can panic the Rust code which is not very nice to handle from Python. If we return a result, though, it is much simpler

File: releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml [hunk 10]
```diff
@@ -0,0 +1,18 @@
+---
+fixes:
+  - |
+      Fix to `attr_map_to_string` method not handling escaped characters in tooltip correctly issue, Issue #750
+      :meth:`attr_map_to_string` now escapes characters in tooltip using `serde_json::to_string()`
+      Added relevant test to ensure it escapes characters correctly.
```
Comment (IvanIsCoding) [inline releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml:6]:
```suggestion
      :func:`.graphviz_draw` can now handle special characters
```

**Review by IvanIsCoding — APPROVED** [review]

File: releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+
+                import rustworkx as rx
+                from rustworkx.visualization import graphviz_draw
+
+                graphviz_draw(
+                    rx.generators.path_graph(2),
+                    filename="graph.svg",
+                    image_type="svg",
+                    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
+                )
```
Comment (IvanIsCoding) [inline releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml:16]:
```suggestion
                graphviz_draw(
                    rx.generators.path_graph(2),
                    image_type="svg",
                    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
                )
```

File: releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml [hunk 12]
```diff
@@ -0,0 +1,15 @@
...
+          .. jupyter-execute::
+
+                import rustworkx as rx
+                from rustworkx.visualization import graphviz_draw
+
+                graphviz_draw(
+                    rx.generators.path_graph(2),
+                    image_type="svg",
+                    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
+                )
```
Comment (IvanIsCoding) [inline releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml:15]:
```suggestion
                    node_attr_fn=lambda x: {"label": "the\nlabel", "tooltip": "the\ntooltip"},
                )
```

**Comment by anushkrishnav** [comment]
Awesome, thank you @IvanIsCoding I was fun working on this, Will work on more issue , I am learning rust for a the past 2 months and been exploring the code base to put my learning into practice thanks for the oppurtunity
